theme: jekyll-theme-minimal
title: Amen Jalal
logo: "/images/IMG_9111.jpeg"
authors:
  Amen_Jalal:
    author-name: Amen Jalal
    author-email: u.jalal@lse.ac.uk
    author-twitter: https://twitter.com/amenjalal_
    author-CV: https://amenjalal94.github.io/docs/CV.pdf
sidebar:
    title: "Works in Progress"
    url: "#works-in-progress"
    title: "Teaching"
    url: "#teaching"
