theme: jekyll-theme-minimal
github: is\_project\_page:false
title: Amen Jalal
logo: "/images/me.jpg"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
email: amenjalal94 at gmail dot com
social-network-links:
  email: "amenjalal94@gmail.com"
  twitter: amenjalal_
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
