theme: jekyll-theme-minimal
title: Amen Jalal
logo: "/images/me.jpg"
authors:
    Amen_Jalal:
      author-name: Amen Jalal
      author-email: amenjalal94@gmail.com
      author-twitter: https://twitter.com/amenjalal_
